### PR TITLE
Create BucketSort.java

### PR DESCRIPTION
**Pull request by GOVINDDIXIT**
Created Java Implementation of Bucket Sort.
One possible solution for issue

### CODE REVIEW

**Comment by GOVINDDIXIT** [comment]
@ambujraj I will add my name in CONTRIBUTORS.md . Once this PR is merged

**Comment by GOVINDDIXIT** [comment]
@ambujraj  pls review

**Comment by GOVINDDIXIT** [comment]
Also updated the name in the Contributors.md
pls review

**Comment by ambujraj** [comment]
add your name to CONTRIBUTORS.md file

**Comment by GOVINDDIXIT** [comment]
@ambujraj updated now you can merge this PR

**Comment by GOVINDDIXIT** [comment]
@ambujraj  is there any problem with this pr

**Comment by GOVINDDIXIT** [comment]
@ambujraj you can merge this pr

**Pull request closed without merging**
